# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.library import Library
from openapi_server.models.new_cluster import NewCluster


class ClusterSpec(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ClusterSpec - a model defined in OpenAPI

        existing_cluster_id: The existing_cluster_id of this ClusterSpec [Optional].
        new_cluster: The new_cluster of this ClusterSpec [Optional].
        libraries: The libraries of this ClusterSpec [Optional].
    """

    existing_cluster_id: Optional[str] = Field(alias="existing_cluster_id", default=None)
    new_cluster: Optional[NewCluster] = Field(alias="new_cluster", default=None)
    libraries: Optional[List[Library]] = Field(alias="libraries", default=None)

ClusterSpec.update_forward_refs()
