# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class FileStorageInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    FileStorageInfo - a model defined in OpenAPI

        destination: The destination of this FileStorageInfo [Optional].
    """

    destination: Optional[str] = Field(alias="destination", default=None)

FileStorageInfo.update_forward_refs()
