# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class JobsCreate200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobsCreate200Response - a model defined in OpenAPI

        job_id: The job_id of this JobsCreate200Response [Optional].
    """

    job_id: Optional[int] = Field(alias="job_id", default=None)

JobsCreate200Response.update_forward_refs()
