# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class JobsRunNow200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobsRunNow200Response - a model defined in OpenAPI

        run_id: The run_id of this JobsRunNow200Response [Optional].
        number_in_job: The number_in_job of this JobsRunNow200Response [Optional].
    """

    run_id: Optional[int] = Field(alias="run_id", default=None)
    number_in_job: Optional[int] = Field(alias="number_in_job", default=None)

JobsRunNow200Response.update_forward_refs()
