# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.maven_library import MavenLibrary
from openapi_server.models.python_py_pi_library import PythonPyPiLibrary
from openapi_server.models.r_cran_library import RCranLibrary


class Library(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Library - a model defined in OpenAPI

        jar: The jar of this Library [Optional].
        egg: The egg of this Library [Optional].
        whl: The whl of this Library [Optional].
        pypi: The pypi of this Library [Optional].
        maven: The maven of this Library [Optional].
        cran: The cran of this Library [Optional].
    """

    jar: Optional[str] = Field(alias="jar", default=None)
    egg: Optional[str] = Field(alias="egg", default=None)
    whl: Optional[str] = Field(alias="whl", default=None)
    pypi: Optional[PythonPyPiLibrary] = Field(alias="pypi", default=None)
    maven: Optional[MavenLibrary] = Field(alias="maven", default=None)
    cran: Optional[RCranLibrary] = Field(alias="cran", default=None)

Library.update_forward_refs()
