# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.library import Library
from openapi_server.models.library_install_status import LibraryInstallStatus


class LibraryFullStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LibraryFullStatus - a model defined in OpenAPI

        library: The library of this LibraryFullStatus [Optional].
        status: The status of this LibraryFullStatus [Optional].
        messages: The messages of this LibraryFullStatus [Optional].
        is_library_for_all_clusters: The is_library_for_all_clusters of this LibraryFullStatus [Optional].
    """

    library: Optional[Library] = Field(alias="library", default=None)
    status: Optional[LibraryInstallStatus] = Field(alias="status", default=None)
    messages: Optional[List[str]] = Field(alias="messages", default=None)
    is_library_for_all_clusters: Optional[bool] = Field(alias="is_library_for_all_clusters", default=None)

LibraryFullStatus.update_forward_refs()
