# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class NotebookTask(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NotebookTask - a model defined in OpenAPI

        notebook_path: The notebook_path of this NotebookTask.
        base_parameters: The base_parameters of this NotebookTask [Optional].
    """

    notebook_path: str = Field(alias="notebook_path")
    base_parameters: Optional[Dict[str, Any]] = Field(alias="base_parameters", default=None)

NotebookTask.update_forward_refs()
