# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunParameters(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunParameters - a model defined in OpenAPI

        jar_params: The jar_params of this RunParameters [Optional].
        notebook_params: The notebook_params of this RunParameters [Optional].
        python_params: The python_params of this RunParameters [Optional].
        spark_submit_params: The spark_submit_params of this RunParameters [Optional].
        python_named_params: The python_named_params of this RunParameters [Optional].
    """

    jar_params: Optional[List[str]] = Field(alias="jar_params", default=None)
    notebook_params: Optional[Dict[str, Any]] = Field(alias="notebook_params", default=None)
    python_params: Optional[List[str]] = Field(alias="python_params", default=None)
    spark_submit_params: Optional[List[str]] = Field(alias="spark_submit_params", default=None)
    python_named_params: Optional[Dict[str, Any]] = Field(alias="python_named_params", default=None)

RunParameters.update_forward_refs()
