# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SparkNodeAwsAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SparkNodeAwsAttributes - a model defined in OpenAPI

        is_spot: The is_spot of this SparkNodeAwsAttributes [Optional].
    """

    is_spot: Optional[bool] = Field(alias="is_spot", default=None)

SparkNodeAwsAttributes.update_forward_refs()
