version: '3.6'
services:
  service:
    build:
      context: .
      target: service
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

  test:
    build:
      context: .
      target: test_runner
    volumes:
      - ./tests/:/tmp/tests/

  builder:
    build:
      context: .
      target: builder

