name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, syncronized]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false