# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.access_control_request import AccessControlRequest


class AccessControlList(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AccessControlList - a model defined in OpenAPI

        access_control_list: The access_control_list of this AccessControlList [Optional].
    """

    access_control_list: Optional[List[AccessControlRequest]] = Field(
        alias="access_control_list", default=None)


AccessControlList.update_forward_refs()
