# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AwsAttributes(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AwsAttributes - a model defined in OpenAPI

        first_on_demand: The first_on_demand of this AwsAttributes [Optional].
        availability: The availability of this AwsAttributes [Optional].
        zone_id: The zone_id of this AwsAttributes [Optional].
        instance_profile_arn: The instance_profile_arn of this AwsAttributes [Optional].
        spot_bid_price_percent: The spot_bid_price_percent of this AwsAttributes [Optional].
        ebs_volume_type: The ebs_volume_type of this AwsAttributes [Optional].
        ebs_volume_count: The ebs_volume_count of this AwsAttributes [Optional].
        ebs_volume_size: The ebs_volume_size of this AwsAttributes [Optional].
        ebs_volume_iops: The ebs_volume_iops of this AwsAttributes [Optional].
        ebs_volume_throughput: The ebs_volume_throughput of this AwsAttributes [Optional].
    """

    first_on_demand: Optional[int] = Field(alias="first_on_demand", default=None)
    availability: Optional[str] = Field(alias="availability", default=None)
    zone_id: Optional[str] = Field(alias="zone_id", default=None)
    instance_profile_arn: Optional[str] = Field(
        alias="instance_profile_arn", default=None)
    spot_bid_price_percent: Optional[int] = Field(
        alias="spot_bid_price_percent", default=None)
    ebs_volume_type: Optional[str] = Field(alias="ebs_volume_type", default=None)
    ebs_volume_count: Optional[int] = Field(alias="ebs_volume_count", default=None)
    ebs_volume_size: Optional[int] = Field(alias="ebs_volume_size", default=None)
    ebs_volume_iops: Optional[int] = Field(alias="ebs_volume_iops", default=None)
    ebs_volume_throughput: Optional[int] = Field(
        alias="ebs_volume_throughput", default=None)


AwsAttributes.update_forward_refs()
