# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.cluster_event_type import ClusterEventType
from openapi_server.models.event_details import EventDetails


class ClusterEvent(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ClusterEvent - a model defined in OpenAPI

        cluster_id: The cluster_id of this ClusterEvent.
        timestamp: The timestamp of this ClusterEvent [Optional].
        type: The type of this ClusterEvent.
        details: The details of this ClusterEvent.
    """

    cluster_id: str = Field(alias="cluster_id")
    timestamp: Optional[int] = Field(alias="timestamp", default=None)
    type: ClusterEventType = Field(alias="type")
    details: EventDetails = Field(alias="details")


ClusterEvent.update_forward_refs()
