# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class CronSchedule(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CronSchedule - a model defined in OpenAPI

        quartz_cron_expression: The quartz_cron_expression of this CronSchedule.
        timezone_id: The timezone_id of this CronSchedule.
        pause_status: The pause_status of this CronSchedule [Optional].
    """

    quartz_cron_expression: str = Field(alias="quartz_cron_expression")
    timezone_id: str = Field(alias="timezone_id")
    pause_status: Optional[str] = Field(alias="pause_status", default=None)


CronSchedule.update_forward_refs()
