# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DbfsStorageInfo(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DbfsStorageInfo - a model defined in OpenAPI

        destination: The destination of this DbfsStorageInfo [Optional].
    """

    destination: Optional[str] = Field(alias="destination", default=None)


DbfsStorageInfo.update_forward_refs()
