# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DockerBasicAuth(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DockerBasicAuth - a model defined in OpenAPI

        username: The username of this DockerBasicAuth [Optional].
        password: The password of this DockerBasicAuth [Optional].
    """

    username: Optional[str] = Field(alias="username", default=None)
    password: Optional[str] = Field(alias="password", default=None)

DockerBasicAuth.update_forward_refs()
