# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.docker_basic_auth import DockerBasicAuth


class DockerImage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DockerImage - a model defined in OpenAPI

        url: The url of this DockerImage [Optional].
        basic_auth: The basic_auth of this DockerImage [Optional].
    """

    url: Optional[str] = Field(alias="url", default=None)
    basic_auth: Optional[DockerBasicAuth] = Field(alias="basic_auth", default=None)

DockerImage.update_forward_refs()
