# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.new_cluster import NewCluster


class JobCluster(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobCluster - a model defined in OpenAPI

        job_cluster_key: The job_cluster_key of this JobCluster.
        new_cluster: The new_cluster of this JobCluster [Optional].
    """

    job_cluster_key: str = Field(alias="job_cluster_key")
    new_cluster: Optional[NewCluster] = Field(alias="new_cluster", default=None)

    @validator("job_cluster_key")
    def job_cluster_key_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("job_cluster_key")
    def job_cluster_key_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("job_cluster_key")
    def job_cluster_key_pattern(cls, value):
        assert value is not None and re.match(r"^[\w\-]+$", value)
        return value


JobCluster.update_forward_refs()
