# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.cron_schedule import CronSchedule
from openapi_server.models.git_source import GitSource
from openapi_server.models.job_cluster import JobCluster
from openapi_server.models.job_email_notifications import JobEmailNotifications
from openapi_server.models.job_task_settings import JobTaskSettings


class JobSettings(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobSettings - a model defined in OpenAPI

        name: The name of this JobSettings [Optional].
        tags: The tags of this JobSettings [Optional].
        tasks: The tasks of this JobSettings [Optional].
        job_clusters: The job_clusters of this JobSettings [Optional].
        email_notifications: The email_notifications of this JobSettings [Optional].
        timeout_seconds: The timeout_seconds of this JobSettings [Optional].
        schedule: The schedule of this JobSettings [Optional].
        max_concurrent_runs: The max_concurrent_runs of this JobSettings [Optional].
        git_source: The git_source of this JobSettings [Optional].
        format: The format of this JobSettings [Optional].
    """

    name: Optional[str] = Field(alias="name", default=None)
    tags: Optional[Dict[str, Any]] = Field(alias="tags", default=None)
    tasks: Optional[List[JobTaskSettings]] = Field(alias="tasks", default=None)
    job_clusters: Optional[List[JobCluster]] = Field(alias="job_clusters", default=None)
    email_notifications: Optional[JobEmailNotifications] = Field(
        alias="email_notifications", default=None)
    timeout_seconds: Optional[int] = Field(alias="timeout_seconds", default=None)
    schedule: Optional[CronSchedule] = Field(alias="schedule", default=None)
    max_concurrent_runs: Optional[int] = Field(
        alias="max_concurrent_runs", default=None)
    git_source: Optional[GitSource] = Field(alias="git_source", default=None)
    format: Optional[str] = Field(alias="format", default=None)


JobSettings.update_forward_refs()
