# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.cluster_instance import ClusterInstance
from openapi_server.models.cluster_spec import ClusterSpec
from openapi_server.models.cron_schedule import CronSchedule
from openapi_server.models.git_source import GitSource
from openapi_server.models.job_cluster import JobCluster
from openapi_server.models.repair_history import RepairHistory
from openapi_server.models.repair_history_item import RepairHistoryItem
from openapi_server.models.run import Run
from openapi_server.models.run_parameters import RunParameters
from openapi_server.models.run_state import RunState
from openapi_server.models.run_task import RunTask
from openapi_server.models.run_type import RunType
from openapi_server.models.trigger_type import TriggerType


class JobsRunsGet200Response(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobsRunsGet200Response - a model defined in OpenAPI

        job_id: The job_id of this JobsRunsGet200Response [Optional].
        run_id: The run_id of this JobsRunsGet200Response [Optional].
        number_in_job: The number_in_job of this JobsRunsGet200Response [Optional].
        creator_user_name: The creator_user_name of this JobsRunsGet200Response [Optional].
        original_attempt_run_id: The original_attempt_run_id of this JobsRunsGet200Response [Optional].
        state: The state of this JobsRunsGet200Response [Optional].
        schedule: The schedule of this JobsRunsGet200Response [Optional].
        tasks: The tasks of this JobsRunsGet200Response [Optional].
        job_clusters: The job_clusters of this JobsRunsGet200Response [Optional].
        cluster_spec: The cluster_spec of this JobsRunsGet200Response [Optional].
        cluster_instance: The cluster_instance of this JobsRunsGet200Response [Optional].
        git_source: The git_source of this JobsRunsGet200Response [Optional].
        overriding_parameters: The overriding_parameters of this JobsRunsGet200Response [Optional].
        start_time: The start_time of this JobsRunsGet200Response [Optional].
        setup_duration: The setup_duration of this JobsRunsGet200Response [Optional].
        execution_duration: The execution_duration of this JobsRunsGet200Response [Optional].
        cleanup_duration: The cleanup_duration of this JobsRunsGet200Response [Optional].
        end_time: The end_time of this JobsRunsGet200Response [Optional].
        trigger: The trigger of this JobsRunsGet200Response [Optional].
        run_name: The run_name of this JobsRunsGet200Response [Optional].
        run_page_url: The run_page_url of this JobsRunsGet200Response [Optional].
        run_type: The run_type of this JobsRunsGet200Response [Optional].
        attempt_number: The attempt_number of this JobsRunsGet200Response [Optional].
        repair_history: The repair_history of this JobsRunsGet200Response [Optional].
    """

    job_id: Optional[int] = Field(alias="job_id", default=None)
    run_id: Optional[int] = Field(alias="run_id", default=None)
    number_in_job: Optional[int] = Field(alias="number_in_job", default=None)
    creator_user_name: Optional[str] = Field(alias="creator_user_name", default=None)
    original_attempt_run_id: Optional[int] = Field(
        alias="original_attempt_run_id", default=None)
    state: Optional[RunState] = Field(alias="state", default=None)
    schedule: Optional[CronSchedule] = Field(alias="schedule", default=None)
    tasks: Optional[List[RunTask]] = Field(alias="tasks", default=None)
    job_clusters: Optional[List[JobCluster]] = Field(alias="job_clusters", default=None)
    cluster_spec: Optional[ClusterSpec] = Field(alias="cluster_spec", default=None)
    cluster_instance: Optional[ClusterInstance] = Field(
        alias="cluster_instance", default=None)
    git_source: Optional[GitSource] = Field(alias="git_source", default=None)
    overriding_parameters: Optional[RunParameters] = Field(
        alias="overriding_parameters", default=None)
    start_time: Optional[int] = Field(alias="start_time", default=None)
    setup_duration: Optional[int] = Field(alias="setup_duration", default=None)
    execution_duration: Optional[int] = Field(alias="execution_duration", default=None)
    cleanup_duration: Optional[int] = Field(alias="cleanup_duration", default=None)
    end_time: Optional[int] = Field(alias="end_time", default=None)
    trigger: Optional[TriggerType] = Field(alias="trigger", default=None)
    run_name: Optional[str] = Field(alias="run_name", default=None)
    run_page_url: Optional[str] = Field(alias="run_page_url", default=None)
    run_type: Optional[RunType] = Field(alias="run_type", default=None)
    attempt_number: Optional[int] = Field(alias="attempt_number", default=None)
    repair_history: Optional[List[RepairHistoryItem]] = Field(
        alias="repair_history", default=None)


JobsRunsGet200Response.update_forward_refs()
