# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.job_settings import JobSettings


class JobsUpdateRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    JobsUpdateRequest - a model defined in OpenAPI

        job_id: The job_id of this JobsUpdateRequest.
        new_settings: The new_settings of this JobsUpdateRequest [Optional].
        fields_to_remove: The fields_to_remove of this JobsUpdateRequest [Optional].
    """

    job_id: int = Field(alias="job_id")
    new_settings: Optional[JobSettings] = Field(alias="new_settings", default=None)
    fields_to_remove: Optional[List[str]] = Field(
        alias="fields_to_remove", default=None)


JobsUpdateRequest.update_forward_refs()
