# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class LogSyncStatus(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LogSyncStatus - a model defined in OpenAPI

        last_attempted: The last_attempted of this LogSyncStatus [Optional].
        last_exception: The last_exception of this LogSyncStatus [Optional].
    """

    last_attempted: Optional[int] = Field(alias="last_attempted", default=None)
    last_exception: Optional[str] = Field(alias="last_exception", default=None)


LogSyncStatus.update_forward_refs()
