# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PipelineTask(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PipelineTask - a model defined in OpenAPI

        pipeline_id: The pipeline_id of this PipelineTask [Optional].
    """

    pipeline_id: Optional[str] = Field(alias="pipeline_id", default=None)

PipelineTask.update_forward_refs()
