# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PythonPyPiLibrary(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PythonPyPiLibrary - a model defined in OpenAPI

        package: The package of this PythonPyPiLibrary.
        repo: The repo of this PythonPyPiLibrary [Optional].
    """

    package: str = Field(alias="package")
    repo: Optional[str] = Field(alias="repo", default=None)


PythonPyPiLibrary.update_forward_refs()
