# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PythonWheelTask(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PythonWheelTask - a model defined in OpenAPI

        package_name: The package_name of this PythonWheelTask [Optional].
        entry_point: The entry_point of this PythonWheelTask [Optional].
        parameters: The parameters of this PythonWheelTask [Optional].
        named_parameters: The named_parameters of this PythonWheelTask [Optional].
    """

    package_name: Optional[str] = Field(alias="package_name", default=None)
    entry_point: Optional[str] = Field(alias="entry_point", default=None)
    parameters: Optional[List[str]] = Field(alias="parameters", default=None)
    named_parameters: Optional[Dict[str, Any]] = Field(
        alias="named_parameters", default=None)


PythonWheelTask.update_forward_refs()
