# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.run_life_cycle_state import RunLifeCycleState
from openapi_server.models.run_result_state import RunResultState


class RunState(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunState - a model defined in OpenAPI

        life_cycle_state: The life_cycle_state of this RunState [Optional].
        result_state: The result_state of this RunState [Optional].
        user_cancelled_or_timedout: The user_cancelled_or_timedout of this RunState [Optional].
        state_message: The state_message of this RunState [Optional].
    """

    life_cycle_state: Optional[RunLifeCycleState] = Field(
        alias="life_cycle_state", default=None)
    result_state: Optional[RunResultState] = Field(alias="result_state", default=None)
    user_cancelled_or_timedout: Optional[bool] = Field(
        alias="user_cancelled_or_timedout", default=None)
    state_message: Optional[str] = Field(alias="state_message", default=None)


RunState.update_forward_refs()
