# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class RunNowInput(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    RunNowInput - a model defined in OpenAPI

        job_id: The job_id of this RunNowInput [Optional].
        idempotency_token: The idempotency_token of this RunNowInput [Optional].
    """

    job_id: Optional[int] = Field(alias="job_id", default=None)
    idempotency_token: Optional[str] = Field(alias="idempotency_token", default=None)


RunNowInput.update_forward_refs()
