# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SparkPythonTask(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SparkPythonTask - a model defined in OpenAPI

        python_file: The python_file of this SparkPythonTask.
        parameters: The parameters of this SparkPythonTask [Optional].
    """

    python_file: str = Field(alias="python_file")
    parameters: Optional[List[str]] = Field(alias="parameters", default=None)


SparkPythonTask.update_forward_refs()
