# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SparkJarTask(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SparkJarTask - a model defined in OpenAPI

        main_class_name: The main_class_name of this SparkJarTask [Optional].
        parameters: The parameters of this SparkJarTask [Optional].
        jar_uri: The jar_uri of this SparkJarTask [Optional].
    """

    main_class_name: Optional[str] = Field(alias="main_class_name", default=None)
    parameters: Optional[List[str]] = Field(alias="parameters", default=None)
    jar_uri: Optional[str] = Field(alias="jar_uri", default=None)

SparkJarTask.update_forward_refs()
