# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.termination_code import TerminationCode
from openapi_server.models.termination_type import TerminationType


class TerminationReason(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TerminationReason - a model defined in OpenAPI

        code: The code of this TerminationReason [Optional].
        type: The type of this TerminationReason [Optional].
        parameters: The parameters of this TerminationReason [Optional].
    """

    code: Optional[TerminationCode] = Field(alias="code", default=None)
    type: Optional[TerminationType] = Field(alias="type", default=None)
    parameters: Optional[Dict[str, Any]] = Field(alias="parameters", default=None)


TerminationReason.update_forward_refs()
