# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.view_type import ViewType


class ViewItem(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ViewItem - a model defined in OpenAPI

        content: The content of this ViewItem [Optional].
        name: The name of this ViewItem [Optional].
        type: The type of this ViewItem [Optional].
    """

    content: Optional[str] = Field(alias="content", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    type: Optional[ViewType] = Field(alias="type", default=None)


ViewItem.update_forward_refs()
